// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebOfTrustConsensus;

namespace WebOfTrustConsensus.Migrations
{
    [DbContext(typeof(ConsensusContext))]
    [Migration("20180820174916_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("WebOfTrustConsensus.KVPendingChanges", b =>
                {
                    b.Property<int>("KVPendingChangesID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Proof");

                    b.Property<int>("TransactionId");

                    b.Property<string>("Value");

                    b.HasKey("KVPendingChangesID");

                    b.HasIndex("TransactionId");

                    b.ToTable("KeyValuePairHistory");
                });

            modelBuilder.Entity("WebOfTrustConsensus.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCommitted");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebOfTrustConsensus.KVPendingChanges", b =>
                {
                    b.HasOne("WebOfTrustConsensus.Transaction", "Transaction")
                        .WithMany("PendingChanges")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
